name: 'rsync to server'

on:
  push:
    branches: [ master ]
    
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --exclude=.git --exclude=.github --exclude=.env
          path: .
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
